### ISSUE TITLE
Are we panicking too much?

### ISSUE THREAD

**Issue by protheory8** [dyc3/stream-autodj#13]
There is a [chapter](https://doc.rust-lang.org/book/ch09-03-to-panic-or-not-to-panic.html) about this in the book. In general, it's mostly recommended to only panic if there either a programming error or if error is not expected. Custom errors also looks more user friendly than a panic message. We can pretty much convert most of `unwrap()` into `?` and it should work fine.

**Comment by dyc3** [comment]
We only explicitly call panic when something goes stupid, a total of 2 times:

1. If the planner makes a plan that is too long, panic because it shouldn't do that.
2. If we encounter a segment in the same song with a duplicate id, panic because the user shouldn't do that.

The only one we should change, if anything, is the latter.

**Comment by protheory8** [comment]
I didn't mean only explicit `panic` calls, it's mostly `unwrap` actually.

**Comment by dyc3** [comment]
Ah ok. I tried using `?` instead of unwrap in some places and the compiler didn't really like it because the function has to return `Option` or `Result`.

Regardless, I think that in general we don't panic unless for user error. For example, if this fails:
```rust
let current_segment = plan.last().unwrap();
```
then we can't continue making the plan anyway, and the conditions that led to panicking is a bug.

I suppose we could make failing to read song segments and failing to extract stuff from regexes a bit friendlier though.

**Comment by protheory8** [comment]
I didn't mean to do it in `main` function, my idea was to move everything into `run` function and main will just parse args, call `run` and print message if there was an error (and also exit with return code 1).

**Comment by protheory8** [comment]
> Regardless, I think that in general we don't panic unless for user error.

I don't think that's how it's supposed to be though. I chatted with people on Rust's Discord server and people seem to say that `panic` is mostly used for cases when something was not supposed to happen (like failed assertions, reaching unreachable code or programmer errors). So from my perspective it seems like panics are comparable to uncaught exceptions in other languages.

**Comment by dyc3** [comment]
Ok, then we should probably do something to fix up error handling then. We definitely panic in some places that are user error.

**Comment by protheory8** [comment]
I'll try to make a PR tomorrow I think.

**Comment by protheory8** [comment]
@dyc3 Really sorry for offtopic comment, but is there an estimate when are you going to start livestreaming again?

**Comment by dyc3** [comment]
Monday the 10th most likely

**Comment by protheory8** [comment]
Kinda unrelated, but chatting with people on Rust's Discord server still kinda leaves me confused on that topic. I personally agree with their approach, but why does the book say other thing?

If you use Discord, you might wanna try chatting with them at https://discord.gg/rust-lang in `#beginners` channel.

**Comment by protheory8** [comment]
I guess this can be closed?
